# typed: false
# frozen_string_literal: true

# Autogenerated by .github/workflows/update-formula.yml — do not edit by hand.
# SHA256s are pinned from the GitHub release assets after their build-provenance
# attestations are verified against the hellbox release workflow.
class Hellbox < Formula
  desc "Run native DOOM inside an AWS Lambda MicroVM, streamed to a browser tab"
  homepage "https://github.com/somoore/hellbox"
  version "1.0.11"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/somoore/hellbox/releases/download/v1.0.11/hellbox-macos-arm64"
      sha256 "49d1c38b2e677c1a8017965ea9ade393c28bc3d9ca70bf52b4a21a01a9494950"
    end
    on_intel do
      url "https://github.com/somoore/hellbox/releases/download/v1.0.11/hellbox-macos-x86_64"
      sha256 "2e4f7f729c3f7a1a3ed08eed10bfa8d61e3c457a129c634a4aa5265b0b0b0d46"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/somoore/hellbox/releases/download/v1.0.11/hellbox-linux-arm64"
      sha256 "dc09cca745e5c83cd397d3f53b7a2c9903ea526246ea1e5641a72ad1911bb464"
    end
    on_intel do
      url "https://github.com/somoore/hellbox/releases/download/v1.0.11/hellbox-linux-x86_64"
      sha256 "e054760d553b82421273d5e92ad07efaf209e5ddbdb46399224b2ce066db1cca"
    end
  end

  def install
    bin.install Dir["hellbox-*"].first => "hellbox"
  end

  def caveats
    <<~CAVEATS
      hellbox drives AWS resources and builds its MicroVM image from the
      Hellbox repo's capsule/ directory:
        git clone https://github.com/somoore/hellbox
        cd hellbox && ./deploy.sh   # uses this brew-installed binary
    CAVEATS
  end

  test do
    assert_match "hellbox", shell_output("#{bin}/hellbox --version")
  end
end
