# typed: false
# frozen_string_literal: true

# Autogenerated by .github/workflows/update-formula.yml — do not edit by hand.
# SHA256s are pinned from the GitHub release assets after their build-provenance
# attestations are verified against the hellbox release workflow.
class Hellbox < Formula
  desc "Run native DOOM inside an AWS Lambda MicroVM, streamed to a browser tab"
  homepage "https://github.com/somoore/hellbox"
  version "1.0.17"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/somoore/hellbox/releases/download/v1.0.17/hellbox-macos-arm64"
      sha256 "2506de82552c547af5cc2b29386e8747a960cf279834dbe0a0be6938ce349312"
    end
    on_intel do
      url "https://github.com/somoore/hellbox/releases/download/v1.0.17/hellbox-macos-x86_64"
      sha256 "440811d6529cc8f5cd9e7a67d622f3173d99ef7e085aad6881d8244f2fbba2ec"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/somoore/hellbox/releases/download/v1.0.17/hellbox-linux-arm64"
      sha256 "18c22d144ff94365b924951007fdda35af894029f4780a0e4dd8590d05249533"
    end
    on_intel do
      url "https://github.com/somoore/hellbox/releases/download/v1.0.17/hellbox-linux-x86_64"
      sha256 "3ff770a0b423a4cb0225d279704f020f87c7db282b576ef3e3517a748dfc3240"
    end
  end

  def install
    bin.install Dir["hellbox-*"].first => "hellbox"
  end

  def caveats
    <<~CAVEATS
      hellbox drives AWS resources and builds its MicroVM image from the
      Hellbox repo's capsule/ directory:
        git clone https://github.com/somoore/hellbox
        cd hellbox && ./deploy.sh   # uses this brew-installed binary
    CAVEATS
  end

  test do
    assert_match "hellbox", shell_output("#{bin}/hellbox --version")
  end
end
