# typed: false
# frozen_string_literal: true

# Autogenerated by .github/workflows/update-formula.yml — do not edit by hand.
# SHA256s are pinned from the GitHub release assets after their build-provenance
# attestations are verified against the hellbox release workflow.
class Hellbox < Formula
  desc "Run native DOOM inside an AWS Lambda MicroVM, streamed to a browser tab"
  homepage "https://github.com/somoore/hellbox"
  version "1.0.4"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/somoore/hellbox/releases/download/v1.0.4/hellbox-macos-arm64"
      sha256 "b4a7753d1c52dac5e33096316e1c7792240fa0a11419dbce855096f1f06c393a"
    end
    on_intel do
      url "https://github.com/somoore/hellbox/releases/download/v1.0.4/hellbox-macos-x86_64"
      sha256 "e3bceb092bd5f929bf14f33c0b5fd5d8c798048b5f5a061ad3069abc296b6a3a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/somoore/hellbox/releases/download/v1.0.4/hellbox-linux-arm64"
      sha256 "80661d4cad4a9558c0177fc1446546a4a625527aeabe82bfe195bf2ecece3f63"
    end
    on_intel do
      url "https://github.com/somoore/hellbox/releases/download/v1.0.4/hellbox-linux-x86_64"
      sha256 "2bb241578bd3d01ca308bb11fd444e359aba455a74141de1a29c90354186208e"
    end
  end

  def install
    bin.install Dir["hellbox-*"].first => "hellbox"
  end

  def caveats
    <<~EOS
      hellbox drives AWS resources and builds its MicroVM image from the
      Hellbox repo's capsule/ directory:
        git clone https://github.com/somoore/hellbox
        cd hellbox && ./deploy.sh   # uses this brew-installed binary
    EOS
  end

  test do
    assert_match "hellbox", shell_output("#{bin}/hellbox --version")
  end
end
